### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by trukhinyuri** [clausreinke/modules.js#1]
I want to use [Sourcegraph](https://sourcegraph.com) for modules.js code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/clausreinke/modules.js. (It should only take 30 seconds.)

Thank you!

**Comment by clausreinke** [comment]
No thanks. Note that the ideas in this repo, though extensively documented in the blog post, would need to be reevaluated carefully if you actually wanted to use it today - browser engines, standards, and tools/libraries have moved on over the last years, so I doubt one would still want to use it for anything but learning purposes. Which is why the repo is no longer active.
